#!/bin/bash
#
#Yl1, Praks 7 Kevin Tropin
#
echo -n "Sisestage vanus: " 
read vanus
if test $vanus -ge 0 -a $vanus -lt 11
then
echo "Laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then
echo "Nooruk"
elif test $vanus -ge 18 -a $vanus -lt 65
then
echo "Täiskasvanud"
elif test $vanus -ge 65
then
echo "Senjoor"
else
echo "Vigane sisend"
fi
#
# Skripti lõpetamine
